# Generated by Django 4.2.7 on 2024-02-02 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0004_alter_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
