# Generated by Django 4.2.7 on 2024-02-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0006_alter_category_name_alter_home_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
